# Generated by Django 5.0.6 on 2026-09-30 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('university', 'University / College'), ('high_school', 'High School'), ('organization', 'Organisation')], default='university', max_length=24)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('allowed_email_domains', models.JSONField(default=list, help_text='e.g. ["alche.ac.mu", "student.alche.ac.mu"]')),
                ('awards_enabled', models.BooleanField(default=True)),
                ('awards_program_name', models.CharField(default='Campus Clubs Excellence Awards', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#0284c7', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.institution'),
        ),
    ]
