# Generated by Django 5.0.6 on 2026-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_licenceinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Campus mark shown after sign-in (never on the public ClubConnect landing).', max_length=255),
        ),
    ]
