# Generated by Django 5.0.6 on 2026-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_supportticket_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='academic_year_label',
            field=models.CharField(blank=True, help_text='Optional override, e.g. 2025-2026. If empty, ClubConnect derives the year from academic_year_start_month.', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='academic_year_start_month',
            field=models.PositiveSmallIntegerField(default=8, help_text='Month the campus academic year begins (1-12). Display and reports follow this campus, not a hardcoded calendar.'),
        ),
        migrations.AddField(
            model_name='institution',
            name='privacy_contact_email',
            field=models.EmailField(blank=True, help_text='Campus data-protection contact. Shown on the Trust page for this institution after sign-in.', max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='report_deadline_day',
            field=models.PositiveSmallIntegerField(default=5, help_text='Day of month leaders should file the monthly report.'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='staff_email_domains',
            field=models.JSONField(default=list, help_text='Staff and lecturer mail, e.g. ["alueducation.com"]'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='student_email_domains',
            field=models.JSONField(default=list, help_text='Student school mail, e.g. ["alustudent.com"]'),
        ),
    ]
