# Generated by Django 5.0.6 on 2026-10-03 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_academic_year_and_handover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusCommitteeHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_email', models.EmailField(max_length=254)),
                ('outgoing_committee', models.JSONField(blank=True, default=list)),
                ('incoming_committee', models.JSONField(blank=True, default=list)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('achievements_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nominated', 'Submitted to campus administrator'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='nominated', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_handovers_confirmed', to=settings.AUTH_USER_MODEL)),
                ('incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campus_handovers_incoming', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_handovers', to='accounts.institution')),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus_handovers_outgoing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
