# Generated by Django 5.0.6 on 2026-10-03 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_campus_committee_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='member_grant_amount',
            field=models.DecimalField(decimal_places=2, default=7, help_text='Grant per unique student per academic year. Split evenly across the clubs that student belongs to.', max_digits=12),
        ),
        migrations.AddField(
            model_name='institution',
            name='member_grant_currency',
            field=models.CharField(default='USD', help_text='ISO currency for the per-member grant (USD, RWF, EUR, …).', max_length=8),
        ),
        migrations.AddField(
            model_name='institution',
            name='membership_census_open',
            field=models.BooleanField(default=False, help_text='When on, students may declare or request the clubs they belong to. Committee Head toggles this.'),
        ),
        migrations.AddField(
            model_name='institution',
            name='membership_census_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='membership_census_opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_membership_windows', to=settings.AUTH_USER_MODEL),
        ),
    ]
