# Generated by Django 5.0.6

import apps.evidence.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0001_initial"),
        ("impact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="file",
            field=models.FileField(blank=True, upload_to=apps.evidence.models.evidence_upload_path),
        ),
        migrations.AddField(
            model_name="evidence",
            name="impact_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence_items",
                to="impact.impactproject",
            ),
        ),
    ]
