# Generated by Django 5.0.6 on 2026-09-01 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_collaborations', to=settings.AUTH_USER_MODEL)),
                ('initiating_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_collaborations', to='clubs.club')),
                ('partner_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collaborations', to='clubs.club')),
            ],
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.CheckConstraint(check=models.Q(('initiating_club', models.F('partner_club')), _negated=True), name='collaboration_distinct_clubs'),
        ),
    ]
