# Generated by Django 5.0.6 on 2026-09-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_institution_user_institution'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='charter_statement',
            field=models.TextField(blank=True, help_text='Why this club should be recognised at the institution.'),
        ),
        migrations.AddField(
            model_name='club',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='accounts.institution'),
        ),
        migrations.AddField(
            model_name='club',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(max_length=220),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='unique_club_slug_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_club_name_per_institution'),
        ),
    ]
