# Generated by Django 5.0.6 on 2026-10-02 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_charter_statement_club_institution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_email', models.EmailField(max_length=254)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('achievements_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('accepted', 'Accepted by incoming'), ('confirmed', 'Confirmed by committee'), ('declined', 'Declined')], default='nominated', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='clubs.club')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_confirmed', to=settings.AUTH_USER_MODEL)),
                ('incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_incoming', to=settings.AUTH_USER_MODEL)),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_outgoing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
