# Generated by Django 5.0.6 on 2026-10-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_academic_year_and_handover'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershiphandover',
            name='incoming_committee',
            field=models.JSONField(blank=True, default=list, help_text='[{name, email, position}, ...] who take office when the Committee Head confirms.'),
        ),
        migrations.AddField(
            model_name='leadershiphandover',
            name='outgoing_committee',
            field=models.JSONField(blank=True, default=list, help_text='[{name, email, position}, ...] as submitted by the outgoing club leader.'),
        ),
        migrations.AlterField(
            model_name='leadershiphandover',
            name='status',
            field=models.CharField(choices=[('nominated', 'Submitted to committee head'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed by committee'), ('declined', 'Declined')], default='nominated', max_length=20),
        ),
    ]
