# Generated by Django 5.0.6 on 2026-09-01 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('objective', models.TextField()),
                ('activities_summary', models.TextField(blank=True)),
                ('beneficiaries_description', models.TextField()),
                ('estimated_beneficiaries_count', models.PositiveIntegerField(default=0)),
                ('outcomes', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('lessons_learned', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_projects', to='clubs.club')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
