# Generated by Django 5.0.6 on 2026-09-01 20:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('explanation', models.TextField()),
                ('evidence_summary', models.TextField(blank=True)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version_metadata', models.JSONField(blank=True, default=dict)),
                ('accepted_as_is', models.BooleanField(blank=True, null=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='evaluation.score')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
