# Generated by Django 5.0.6 on 2026-09-01 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('objective', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('expected_participation', models.PositiveIntegerField(default=0)),
                ('actual_participation', models.PositiveIntegerField(blank=True, null=True)),
                ('beneficiaries_description', models.TextField(blank=True)),
                ('impact_metrics', models.JSONField(blank=True, default=dict)),
                ('report_text', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='draft', max_length=25)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clubs.club')),
                ('collaborating_clubs', models.ManyToManyField(blank=True, related_name='collaborated_activities', to='clubs.club')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
                'indexes': [models.Index(fields=['club', 'status'], name='activities__club_id_f10ef3_idx')],
            },
        ),
    ]
